config/routes.rb
Rails.application.routes.draw do

  resources :fundamentals, only: %i(new create index show) do
    resources :skills, only: %i(new create index show destroy)
  end

  # NOTE to avoid triple nesting. should I entirely avoid nesting?
  resources :skills, only: %i() do
    resources :drills, only: %i(new create index show)
  end

  root to: 'dashboards#show'
  get '/charts' => 'charts#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'coaches#new'

  get 'auth/google_oauth2/callback' => 'google_drives#create'

  post 'diver_practices/set_minutes_late' => 'diver_practices#set_minutes_late'
  post 'diver_practices/set_excuse' => 'diver_practices#set_excuse'

  resource :dashboard, only: :show
  resource :settings, only: :show
  resources :coaches, only: [:create, :update, :show]
  resources :teams do
    resources :practices, only: [:destroy] do
      collection do
        post :add_practices
        post :export_practices
      end
    end
    resource :attendance, only: :show do
      collection do
        post :update_date_range
      end
    end
    resource :attendance_report, only: :show do
      get 'diver'
    end
  end
  resources :divers do
    member do
      post :deactivate
    end
    resources :diver_practices do
      member do
        post :toggle_attendance
      end
    end
    resources :lists, only: [:new, :edit, :create, :show, :update, :destroy] do
      resources :list_dives, only: [:new, :create]
    end
  end
  # NOTE: should be nested resource, not sure how to do the form_for from dashboard that way
  resources :goals, only: [:create, :edit, :index]
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :diver
  has_many :list_dives, dependent: :destroy
  has_many :dives, through: :list_dives

  accepts_nested_attributes_for :list_dives,
    allow_destroy: true,
    reject_if: :all_blank
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_diver
  before_action :set_dives, only: [:new, :edit]
  before_action :set_list, only: [:edit, :update, :destroy]

  def new
    @list = List.new
  end

  def create
     @diver.lists.create(list_params)
  end

  def show
    @list = @diver.lists.find(params[:id])
  end

  def update
    @list.update_attributes(list_params)
    @lists = @diver.lists
  end

  def destroy
    @list.destroy
  end

  private

  def set_diver
    @diver = @current_coach.divers.find(params[:diver_id])
  end

  def set_dives
    @dives = Dive.all
  end

  def set_list
    @list = @diver.lists.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :description, list_dives_attributes: [:dive_id, :notes, :_destroy, :id])
  end
end

app/views/lists/_edit_form.html.erb
<%= form_for setup_list(@list), url: diver_list_path(@diver, @list), remote: true do |f| %>
  <div class="form-group">
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, { autofocus: true, class: 'form-control' } %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description, { class: 'form-control' } %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 text-center">
      <h3>Dives</h3>
    </div>
  </div>

  <%= f.fields_for :list_dives do |ff| %>
    <div>
      <div class="row">
        <div class="col-xs-4">
          <div class="form-group">
            <div class="field">
              <%= ff.select :dive_id, options_from_collection_for_select(@dives, :id, :display_description, ff.object.try(:dive_id)), { include_blank: true }, { class: 'form-control js-dive-select' } %>
            </div>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="form-group">
            <div class="field">
              <%= ff.text_field :notes, { placeholder: 'Enter a Note!', class: 'form-control' } %>
            </div>
          </div>
        </div>

      <% if ff.object.persisted? %>
        <div class="col-xs-2">
          <div class="form-group">
            <div class="field">
              <%= ff.check_box :_destroy %>
              <%= ff.label :_destroy, "Check to Delete" %>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Save", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/lists/_form.html.erb
<%= form_for setup_list(@list), url: diver_lists_path(@diver), remote: true do |f| %>
  <div class="form-group">
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, { autofocus: true, class: 'form-control' } %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description, { class: 'form-control' } %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 text-center">
      <h3>Dives</h3>
    </div>
  </div>

  <%= f.fields_for :list_dives do |ff| %>
    <div>
      <div class="row">
        <div class="col-xs-4">
          <div class="form-group">
            <div class="field">
              <%= ff.select :dive_id, options_from_collection_for_select(@dives, :id, :display_description), { include_blank: true }, { class: 'form-control js-dive-select' } %>
            </div>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="form-group">
            <div class="field">
              <%= ff.text_field :notes, { placeholder: 'Enter a Note!', class: 'form-control' } %>
            </div>
          </div>
        </div>

      <% if ff.object.persisted? %>
        <div class="col-xs-2">
          <div class="form-group">
            <div class="field">
              <%= ff.check_box :_destroy %>
              <%= ff.label :_destroy, "Check to Delete" %>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Save", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-list fa-fw"></i> <%= list.name %>
      <div class="pull-right">
        <%= link_to edit_diver_list_path(list.diver, list), remote: true do %>
          <i class="fa fa-pencil-square-o"></i>
        <% end %>
        <%= link_to diver_list_path(list.diver, list), remote: true, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <i class="fa fa-trash-o"></i>
        <% end %>
      </div>
      </div>
      <div class="panel-body">
        <%= render partial: 'shared/list_table', locals: { list: list } %>
      </div>
    </div>
  </div>
</div>

app/views/lists/create.js.erb
$('#lists').html("<%= escape_javascript(render @diver.lists) %>");
$('#list-form').slideUp(350);
$('#add-list-button').show();

app/views/lists/destroy.js.erb
$('#lists').html("<%= escape_javascript(render @diver.lists) %>");

app/views/lists/edit.js.erb
$('#list-form').html("<%= escape_javascript(render 'edit_form') %>");
$('.js-dive-select').select2({
  placeholder: "Choose a dive",
  allowClear: true,
  width: '100%'
});
$('#list-form').slideDown(350);

app/views/lists/new.js.erb
$('#list-form').html("<%= escape_javascript(render 'form') %>");
$('#add-list-button').hide();
$('.js-dive-select').select2({
  placeholder: "Choose a dive",
  allowClear: true,
  width: '100%'
});
$('#list-form').slideDown(350);

app/views/lists/show.html.erb
<h1><%= "#{@list.name} (#{@list.dives.count} dives)" %></h1>

Dives:
<ul>
  <% @list.dives.each do |dive| %>
    <li><%= "#{dive.number} #{dive.height}M -- #{dive.description}" %></li>
  <% end %>
</ul>

<%= link_to('Add a Dive', new_diver_list_list_dive_path(list_id: @list.id)) %>

app/views/lists/update.js.erb
$('#lists').html("<%= escape_javascript(render @lists) %>");
$('#list-form').slideUp(350);