config/routes.rb
Rails.application.routes.draw do

  resources :fundamentals, only: %i(new create index show) do
    resources :skills, only: %i(new create index show destroy)
  end

  # NOTE to avoid triple nesting. should I entirely avoid nesting?
  resources :skills, only: %i() do
    resources :drills, only: %i(new create index show)
  end

  root to: 'dashboards#show'
  get '/charts' => 'charts#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'coaches#new'

  get 'auth/google_oauth2/callback' => 'google_drives#create'

  post 'diver_practices/set_minutes_late' => 'diver_practices#set_minutes_late'
  post 'diver_practices/set_excuse' => 'diver_practices#set_excuse'

  resource :dashboard, only: :show
  resource :settings, only: :show
  resources :coaches, only: [:create, :update, :show]
  resources :teams do
    resources :practices, only: [:destroy] do
      collection do
        post :add_practices
        post :export_practices
      end
    end
    resource :attendance, only: :show do
      collection do
        post :update_date_range
      end
    end
    resource :attendance_report, only: :show do
      get 'diver'
    end
  end
  resources :divers do
    member do
      post :deactivate
    end
    resources :diver_practices do
      member do
        post :toggle_attendance
      end
    end
    resources :lists, only: [:new, :edit, :create, :show, :update, :destroy] do
      resources :list_dives, only: [:new, :create]
    end
  end
  # NOTE: should be nested resource, not sure how to do the form_for from dashboard that way
  resources :goals, only: [:create, :edit, :index]
end

app/models/fundamental.rb
class Fundamental < ActiveRecord::Base
  has_many :skills, dependent: :destroy

  validates :name, presence: true
end

app/controllers/fundamentals_controller.rb
class FundamentalsController < ApplicationController
  before_action :set_fundamental, only: [:show, :destroy]

  # GET /fundamentals
  # GET /fundamentals.json
  def index
    @fundamentals = Fundamental.all
  end

  # GET /fundamentals/1
  # GET /fundamentals/1.json
  def show
  end

  # GET /fundamentals/new
  def new
    @fundamental = Fundamental.new
  end

  # POST /fundamentals
  # POST /fundamentals.json
  def create
    @fundamental = Fundamental.new(fundamental_params)

    respond_to do |format|
      if @fundamental.save
        format.html { redirect_to @fundamental, success: 'Fundamental was successfully created.' }
        format.json { render :show, status: :created, location: @fundamental }
      else
        format.html { render :new }
        format.json { render json: @fundamental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fundamentals/1
  # DELETE /fundamentals/1.json
  def destroy
    @fundamental.destroy
    respond_to do |format|
      format.html { redirect_to fundamentals_url, success: 'Fundamental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fundamental
      @fundamental = Fundamental.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fundamental_params
      params.require(:fundamental).permit(:name)
    end
end

app/helpers/fundamentals_helper.rb
module FundamentalsHelper
end

app/views/fundamentals/_form.html.erb
<%= form_for(@fundamental) do |f| %>
  <% if @fundamental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fundamental.errors.count, "error") %> prohibited this fundamental from being saved:</h2>

      <ul>
      <% @fundamental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/fundamentals/index.html.erb
<h1>Diving Fundamentals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fundamentals.each do |fundamental| %>
      <tr>
        <td><%= link_to fundamental.name, fundamental %></td>
        <td><%= link_to 'Destroy', fundamental, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fundamental', new_fundamental_path %>

app/views/fundamentals/new.html.erb
<h1>New Fundamental</h1>

<%= render 'form' %>

<%= link_to 'Back', fundamentals_path %>

app/views/fundamentals/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @fundamental.name %>
</p>

<h3>Skills</h3>
<ul>
  <% @fundamental.skills.each do |skill| %>
    <li><%= link_to skill.name, [@fundamental, skill] %></li>
  <% end %>
</ul>

<%= link_to 'Add Skill', new_fundamental_skill_path(@fundamental) %>
<%= link_to 'Back', fundamentals_path %>