config/routes.rb
Rails.application.routes.draw do

  resources :fundamentals, only: %i(new create index show) do
    resources :skills, only: %i(new create index show destroy)
  end

  # NOTE to avoid triple nesting. should I entirely avoid nesting?
  resources :skills, only: %i() do
    resources :drills, only: %i(new create index show)
  end

  root to: 'dashboards#show'
  get '/charts' => 'charts#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'coaches#new'

  get 'auth/google_oauth2/callback' => 'google_drives#create'

  post 'diver_practices/set_minutes_late' => 'diver_practices#set_minutes_late'
  post 'diver_practices/set_excuse' => 'diver_practices#set_excuse'

  resource :dashboard, only: :show
  resource :settings, only: :show
  resources :coaches, only: [:create, :update, :show]
  resources :teams do
    resources :practices, only: [:destroy] do
      collection do
        post :add_practices
        post :export_practices
      end
    end
    resource :attendance, only: :show do
      collection do
        post :update_date_range
      end
    end
    resource :attendance_report, only: :show do
      get 'diver'
    end
  end
  resources :divers do
    member do
      post :deactivate
    end
    resources :diver_practices do
      member do
        post :toggle_attendance
      end
    end
    resources :lists, only: [:new, :edit, :create, :show, :update, :destroy] do
      resources :list_dives, only: [:new, :create]
    end
  end
  # NOTE: should be nested resource, not sure how to do the form_for from dashboard that way
  resources :goals, only: [:create, :edit, :index]
end

app/models/diver.rb
class Diver < ActiveRecord::Base
  belongs_to :team
  has_many :coaches, through: :team
  has_many :lists, dependent: :destroy
  has_many :dives, through: :lists
  has_many :diver_practices
  has_many :practices, through: :diver_practices
  has_many :diver_goals, dependent: :destroy
  has_many :goals, through: :diver_goals
  has_many :goal_dives, through: :goals, source: :dive

  scope :active, -> { where(deactivated_at: nil) }
  scope :inactive, -> { where.not(deactivated_at: nil) }

  def deactivated?
    deactivated_at.present?
  end
end

app/controllers/divers_controller.rb
class DiversController < ApplicationController
  before_action :all_teams, only: [:edit, :create, :update, :destroy]
  before_action :all_divers, only: [:index, :create, :update, :destroy]
  before_action :set_diver, only: [:edit, :update, :destroy, :deactivate]
  before_action :all_dives, only: [:show]

  def new
    @diver = Diver.new
    @teams = @current_coach.teams
  end

  def create
    @diver = Diver.create(diver_params)
    redirect_to dashboard_path, flash: { success: "Diver Created!" }
  end

  def show
    @diver = Diver.find(params[:id])
  end

  def update
    @diver.update_attributes(diver_params)
  end

  def destroy
    @diver.destroy
  end

  def deactivate
    @diver.update(
      deactivated_at: params[:deactivated_at],
      deactivation_reason: params[:deactivation_reason]
    )
    remove_diver_practices_after_deactivation!
    redirect_to dashboard_path, { flash: { success: 'Diver has been deactivated!' } }
  end

  private

  def set_diver
    @diver = @current_coach.divers.find(params[:id])
  end

  def diver_params
    params.require(:diver).permit(:name, :join_date, :birthday, :email, :phone, :team_id)
  end

  def remove_diver_practices_after_deactivation!
    @diver.diver_practices.joins(:practice).where("practices.date > (?)", @diver.deactivated_at).destroy_all
  end
end

app/views/divers/_diver.html.erb
<tr>
  <td><%= link_to(diver.name, diver_path(diver)) %></td>
  <td><%= diver.birthday %></td>
  <td><%= diver.dives.count %></td>
  <td>
    <%= link_to edit_diver_path(diver), remote: true do %>
      <i class="fa fa-pencil-square-o"></i>
    <% end %>
    <%= link_to diver_path(diver), remote: true, method: :delete, data: { confirm: 'Are you sure?' } do %>
      <i class="fa fa-trash-o"></i>
    <% end %>
  </td>
</tr>

app/views/divers/_form.html.erb
<%= form_for @diver || Diver.new do |f| %>
  <div class="form-group">
    <div class="field">
      <%= f.label :team_id %><br />
      <%= f.select :team_id, options_from_collection_for_select(@teams, "id", "name"), {}, { class: 'form-control' } %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, { autofocus: true, class: 'form-control' } %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :join_date %><br />
      <%= f.date_field :join_date, { class: 'form-control' } %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :birthday %><br />
      <%= f.date_field :birthday, { class: 'form-control' } %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email, { class: 'form-control' } %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :phone %><br />
      <%= f.text_field :phone, { class: 'form-control' } %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/divers/_goals.html.erb
<div id='diver-<%= diver.id %>-goals'>
  <p class="huge">1M Goals: <%= diver.goals.one_meter.map(&:number).join(', ') %></p>
  <p class="huge">3M Goals: <%= diver.goals.three_meter.map(&:number).join(', ') %></p>
  <p class="huge">Platform Goals: <%= diver.goals.platform.map(&:number).join(', ') %></p>

  <hr>
  <%= render '/goals/form', remote: true, diver_id: diver.id %>
</div>

app/views/divers/create.js.erb
$('#divers-count').html("<%= @divers.count %>");
$('#divers').html("<%= escape_javascript(render @divers) %>");
// this is necessary because the diver counts will change
$('#teams').html("<%= escape_javascript(render @teams) %>");
$('#diver-form').slideUp(350);
$('#add-diver-button').show();

app/views/divers/destroy.js.erb
$('#divers-count').html("<%= @divers.count %>");
$('#divers').html("<%= escape_javascript(render @divers) %>");
// this is necessary because the diver counts will change
$('#teams').html("<%= escape_javascript(render @teams) %>");

app/views/divers/edit.js.erb
$('#diver-form').html("<%= escape_javascript(render 'form') %>");
$('#diver-form').slideDown(350);

app/views/divers/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <% @divers.each do |diver| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= diver.name %>
          </div>
          <div class="panel-body">
            <% if diver.lists.any? %>
              <% diver.lists.each do |list| %>
                <p class='text-center'><%= list.name.capitalize %></p>
                <%= render partial: 'shared/list_table', locals: { list: list } %>
              <% end %>
            <% else %>
              <p class="text-muted">No lists yet...</p>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/divers/new.js.erb
$('#diver-form').html("<%= escape_javascript(render 'form') %>");
$('#add-diver-button').hide();
$('#diver-form').slideDown(350);

app/views/divers/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1 class="page-header">
      <%= @diver.name %>
      <% unless @diver.deactivated_at.present? %>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deactivation-modal">
          Deactivate
        </button>
      <% end %>
    </h1>
  </div>
</div>

<%= render 'divers/goals', diver: @diver %>

<div class="row hide">
  <div class="col-xs-12">
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2" id="list-form" style="display:none;"></div>
    </div>
    <div class="pull-right">
      <%= link_to('Add a List', new_diver_list_path(@diver), remote: true, class: 'btn btn-primary', id: 'add-list-button') %>
    </div>
  </div>
</div>

<% unless @diver.deactivated_at.present? %>
  <div class="modal fade" id="deactivation-modal" role="dialog" aria-labelledby="practices-modal-label">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Deactivate <%= @diver.name %></h4>
        </div>
        <!-- TODO: add validation to prevent submitting both -->
        <%= form_tag(deactivate_diver_path(@diver), class: 'form-horizontal') do %>
          <div class="modal-body">
            <div class="form-group">
              <label class="col-sm-2 control-label" for="deactivated_at">Date</label>
              <div class="col-sm-10">
                <%= date_field_tag :deactivated_at, Date.today, { class: 'form-control' } %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label" for="deactivation_reason">Reason</label>
              <div class="col-sm-10">
                <%= text_field_tag :deactivation_reason, 'Why is this diver being deactivated?', class: 'form-control' %>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= submit_tag "Deactivate", class: 'btn btn-danger', data: { disable_with: 'Loading...' } %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<div id='lists' class='hide'>
  <%= render @diver.lists %>
</div>

app/views/divers/update.js.erb
$('#divers').html("<%= escape_javascript(render @divers) %>");
// this is necessary because the diver counts will change
$('#teams').html("<%= escape_javascript(render @teams) %>");
$('#diver-form').slideUp(350);