config/routes.rb
Rails.application.routes.draw do

  resources :fundamentals, only: %i(new create index show) do
    resources :skills, only: %i(new create index show destroy)
  end

  # NOTE to avoid triple nesting. should I entirely avoid nesting?
  resources :skills, only: %i() do
    resources :drills, only: %i(new create index show)
  end

  root to: 'dashboards#show'
  get '/charts' => 'charts#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'coaches#new'

  get 'auth/google_oauth2/callback' => 'google_drives#create'

  post 'diver_practices/set_minutes_late' => 'diver_practices#set_minutes_late'
  post 'diver_practices/set_excuse' => 'diver_practices#set_excuse'

  resource :dashboard, only: :show
  resource :settings, only: :show
  resources :coaches, only: [:create, :update, :show]
  resources :teams do
    resources :practices, only: [:destroy] do
      collection do
        post :add_practices
        post :export_practices
      end
    end
    resource :attendance, only: :show do
      collection do
        post :update_date_range
      end
    end
    resource :attendance_report, only: :show do
      get 'diver'
    end
  end
  resources :divers do
    member do
      post :deactivate
    end
    resources :diver_practices do
      member do
        post :toggle_attendance
      end
    end
    resources :lists, only: [:new, :edit, :create, :show, :update, :destroy] do
      resources :list_dives, only: [:new, :create]
    end
  end
  # NOTE: should be nested resource, not sure how to do the form_for from dashboard that way
  resources :goals, only: [:create, :edit, :index]
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :all_teams, :all_divers, :all_dives

  # Overriding Application controller method for more reporting counts
  def all_teams
    @teams = @current_coach.teams.joins("LEFT JOIN practices ON practices.team_id = teams.id LEFT JOIN diver_practices on diver_practices.practice_id = practices.id")
      .where("practices.id IS NULL OR practices.date <= ?", Date.today)
      .select("teams.*, sum(case when diver_practices.was_present then 1 else 0 end) / CASE COUNT(diver_practices.id) WHEN 0 THEN 1.0 ELSE COUNT(diver_practices.id)::float END as attendance_percentage")
      .select("COUNT(DISTINCT practices.id) as practice_count")
      .group("teams.id")
  end
end

app/views/dashboards/_diver_card.html.erb
<div class="col-md-4">
  <% panel_class = diver.deactivated? ? 'panel-danger' : 'panel-info' %>
  <div class="panel <%= panel_class %>">
    <div class="panel-heading">
      <h3 class="panel-title">
        <%= link_to(diver_path(diver)) do %>
          <%= diver.name %> <%= "<small>(Deactivated)</small>".html_safe if diver.deactivated? %>
        <% end %>
      </h3>
    </div>
    <div class="panel-body">
      <dl class="dl-horizontal">
        <dt>Born</dt>
        <dd><%= diver.birthday.try(:strftime, "%m/%d/%Y") || 'Unknown' %></dd>
        <dt>Attended</dt>
        <dd><%= pluralize(diver.attended_practices_count, 'Practice') %></dd>
        <dt>Missed</dt>
        <dd><%= pluralize(diver.missed_practices_count, 'Practice') %></dd>
      </dl>

      <%= link_to '#', remote: true, class: 'pull-right', data: {
        toggle: "modal",
        target: "#new-goal-modal",
        diver_id: diver.id,
        diver_name: diver.name
      } do %>
      <i class="fa fa-plus"></i> New Goal
    <% end %>

    </div>
  </div>
</div>

app/views/dashboards/_diver_cards.html.erb
<div class="row">
  <% if divers.present? %>
    <% divers.each do |diver| %>
      <%= render partial: 'diver_card', locals: { diver: diver } %>
    <% end %>
  <% else %>
    <div class="col-md-3">
      <p class="text-muted">This team has no divers...</p>
    </div>
  <% end %>
</div>

app/views/dashboards/_team_profile.html.erb
<div class="row">
  <div class="col-xs-12 text-right">
    <%= link_to('Record Attendance', team_attendance_path(team), class: 'btn btn-primary') %>
    <div class="btn-group">
      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-cogs"></i><span class="caret"></span>
      </button>
      <ul class="dropdown-menu dropdown-menu-right">
        <li>
          <%= link_to edit_team_path(team), remote: true do %>
            Edit Team Name
          <% end %>
        <li>
          <%= link_to team_path(team), method: :delete, data: { confirm: 'Are you sure?' } do %>
            Delete Team
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-8 col-xs-offset-2" id="team-form-<%= team.id %>" style="display:none;"></div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-primary dashboard-panel">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-users fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <% coach_count = team.coaches.count %>
            <div class="huge" id="coaches-count"><%= coach_count %></div>
            <div><%= 'Coach'.pluralize(coach_count) %></div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-green dashboard-panel">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-anchor fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <% diver_count = team.divers.count %>
            <div class="huge" id="divers-count"><%= diver_count %></div>
            <div><%= 'Diver'.pluralize(diver_count) %></div>
          </div>
        </div>
      </div>
      <a href="<%= divers_path(team_id: team.id) %>">
        <div class="panel-footer">
          <span class="pull-left">View Divers</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-info dashboard-panel">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-trophy fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <% practice_count = team.practices.where("date <= ?", Date.today).count %>
            <div class="huge" id="practices-count"><%= "#{number_to_percentage(team.attendance_percentage * 100)}" %></div>
            <div><%= team.practice_count %> <%= 'Practice'.pluralize(team.practice_count) %></div>
          </div>
        </div>
      </div>
      <a href="<%= team_attendance_report_path(team) %>">
        <div class="panel-footer">
          <span class="pull-left">View Attendance Report</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
</div>

app/views/dashboards/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1 class="page-header">Your Teams</h1>
  </div>
</div>

<% if @teams.any? %>
  <ul class="nav nav-pills">
    <% @teams.each_with_index do |team, index| %>
      <% tab_class = index == 0 ? 'active' : '' %>
      <li role="presentation" class=<%= tab_class %>><a data-toggle="tab" href="#team-<%= team.id %>"><%= team.name %></a></li>
    <% end %>
    <li role="presentation">
      <a data-toggle="modal" data-target="#new-team-modal">
        <i class="fa fa-plus"></i> Add Team
      </a>
    </li>
    <div class="modal fade" id="new-team-modal" role="dialog" aria-labelledby="new-team-modal-label">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="new-team-modal-label">Add a Team!</h4>
          </div>
          <div class="modal-body">
            <%= render '/teams/form' %>
          </div>
        </div>
      </div>
    </div>
  </ul>
<% else %>
  <%= link_to new_team_path, remote: true, class: 'btn btn-primary' do %>
    <i class="fa fa-plus"></i> Add Team</a>
  <% end %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2" id="team-form" style="display:none;"></div>
  </div>
<% end %>

<div class="modal fade" id="new-goal-modal" role="dialog" aria-labelledby="new-goal-modal-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="new-goal-modal-label">Add a Goal</h4>
      </div>
      <div class="modal-body">
        <%= render '/goals/form', remote: false, diver_id: nil %>
      </div>
    </div>
  </div>
</div>

<div class="tab-content">
  <% @teams.each_with_index do |team, index| %>
    <% tab_class = index == 0 ? 'in active' : '' %>
    <div id="team-<%= team.id %>" class="tab-pane fade <%= tab_class %>">
      <%= render partial: 'team_profile', locals: { team: team } %>
      <hr>
    <% divers = team.divers
      .joins("LEFT JOIN diver_practices ON diver_practices.diver_id = divers.id")
      .joins("LEFT JOIN practices ON practices.id = diver_practices.practice_id")
      .where("practices.id IS NULL OR practices.date <= (?)", Date.today)
      .select("divers.*, sum(case when diver_practices.was_present then 1 else 0 end) as attended_practices_count")
      .select("divers.*, sum(case when diver_practices.was_present then 0 else 1 end) as missed_practices_count")
      .group("divers.id").distinct("divers.id")
      .order(deactivated_at: :desc, name: :asc)
    %>
    <div class="text-right">
      <a class="btn btn-primary" style="margin-bottom: 10px;" data-toggle="modal" data-target="#new-diver-modal-<%= team.id %>">
        <i class="fa fa-plus"></i> Add Diver
      </a>
    </div>
    <div class="modal fade" id="new-diver-modal-<%= team.id %>" role="dialog" aria-labelledby="new-diver-modal-label">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="new-team-modal-label">Add a Diver!</h4>
          </div>
          <div class="modal-body">
            <%= render '/divers/form' %>
          </div>
        </div>
      </div>
    </div>
    <%= render partial: 'diver_cards', locals: { divers: divers } %>
    </div>
  <% end %>
</div>